### ISSUE TITLE
선생님 회원가입 서버 에러

### ISSUE THREAD

**Issue by blxckdog7702** [hmu332233/dictation-retrofit#2]
Post /teachers 로 날렸을 때,

안드로이드에서 날리면 500에러가 발생.

하지만 포스트맨에서는 정상 작동

Why?

**Comment by hmu332233** [comment]
task
[retrofit] `setID` 삭제하기
[server] `id` 값 빼고 처리하기

**Comment by blxckdog7702** [comment]
해결됐습니다.
